---
id : 3
n : 4                                 # number of servers
f : 1                                 # number of byzantine servers tolerated
d : 3                                 # number of dispatchers per node

logging: "info"
chainId : "chain"
ledger: ""                            # persistent storage path

maxLeaders: 4                         # max leaderset size, set to 1 to emulate PBFT
batchDurationNsec: 2000000000         # timeout to cut a batch in nanoseconds
batchSizeBytes: 2000000               # batch size in bytes
epochTimeoutNsec: 10000000000         # epoch change time out in nanoseconds
signatureVerification: true           # request signature verification
batchSignature: false                 # batch signatures on commit messages
payloadSharding: false                # light total order broadcast
sigSharding: false                    # request signature verification sharding
watermarkDist: 64                     # low to high watermaks distance in number of batches
checkpointDist: 16                    # checkpoint distance in number of batches
bucketRotationPeriod: 64              # max epoch size in recovery & bucket rotation period in stable mode
clientWatermarkDist: 10000000         # number of parallel requests per client
buckets: 2                            # buckets per leader

# Byzantine behavior
byzantineDuplication: false           # if true nodes do not filter out preprepared or delivered requests
censoring: 0                          # the percentage of requests a malicious node drops [0..100]
byzantineDelay: 0                     # time added to batch timeout in nanoseconds
byzantineAfter: 0                     # Adding Byzantine delay for sequence numbers greater or equal to ByzantineAfter
byzantineUntil: 0                     # Adding Byzantine delay for sequence numbers lees than ByzantineUntil

# Local (sever-side) load generation for testing
requestSize: 500
requestsPerClientCore: 0

useTLS: true                          # Use TLS for both peer-to-peer and client-to-peer communication
serverConnectionBuffer: 2             # Number of seconds the servers need to wait for each-other to establish all connections

self:
  listen: "0.0.0.0:8034"
  caCertFile: "/opt/gopath/src/github.com/IBM/mirbft/sampleconfig/certs/ecdsa/ca.pem"
  keyFile: "/opt/gopath/src/github.com/IBM/mirbft/sampleconfig/certs/ecdsa/server4.key"
  certFile: "/opt/gopath/src/github.com/IBM/mirbft/sampleconfig/certs/ecdsa/server4.pem"
servers:
  certFiles:
    - "/opt/gopath/src/github.com/IBM/mirbft/sampleconfig/certs/ecdsa/server1.pem"
    - "/opt/gopath/src/github.com/IBM/mirbft/sampleconfig/certs/ecdsa/server2.pem"
    - "/opt/gopath/src/github.com/IBM/mirbft/sampleconfig/certs/ecdsa/server3.pem"
    - "/opt/gopath/src/github.com/IBM/mirbft/sampleconfig/certs/ecdsa/server4.pem"
  addresses:
    - "127.0.0.1:8001"
    - "127.0.0.1:8012"
    - "127.0.0.1:8023"
    - "127.0.0.1:8034"