// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messagepb/messagepb.proto

package messagepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	isspb "github.com/hyperledger-labs/mirbft/pkg/pb/isspb"
	requestpb "github.com/hyperledger-labs/mirbft/pkg/pb/requestpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Type:
	//	*Message_Iss
	//	*Message_DummyPreprepare
	Type                 isMessage_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e5db85d23e1fb5b, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Type interface {
	isMessage_Type()
}

type Message_Iss struct {
	Iss *isspb.ISSMessage `protobuf:"bytes,1,opt,name=iss,proto3,oneof"`
}

type Message_DummyPreprepare struct {
	DummyPreprepare *DummyPreprepare `protobuf:"bytes,100,opt,name=dummy_preprepare,json=dummyPreprepare,proto3,oneof"`
}

func (*Message_Iss) isMessage_Type() {}

func (*Message_DummyPreprepare) isMessage_Type() {}

func (m *Message) GetType() isMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Message) GetIss() *isspb.ISSMessage {
	if x, ok := m.GetType().(*Message_Iss); ok {
		return x.Iss
	}
	return nil
}

func (m *Message) GetDummyPreprepare() *DummyPreprepare {
	if x, ok := m.GetType().(*Message_DummyPreprepare); ok {
		return x.DummyPreprepare
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Iss)(nil),
		(*Message_DummyPreprepare)(nil),
	}
}

type DummyPreprepare struct {
	Sn                   uint64           `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Batch                *requestpb.Batch `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DummyPreprepare) Reset()         { *m = DummyPreprepare{} }
func (m *DummyPreprepare) String() string { return proto.CompactTextString(m) }
func (*DummyPreprepare) ProtoMessage()    {}
func (*DummyPreprepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e5db85d23e1fb5b, []int{1}
}

func (m *DummyPreprepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyPreprepare.Unmarshal(m, b)
}
func (m *DummyPreprepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyPreprepare.Marshal(b, m, deterministic)
}
func (m *DummyPreprepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyPreprepare.Merge(m, src)
}
func (m *DummyPreprepare) XXX_Size() int {
	return xxx_messageInfo_DummyPreprepare.Size(m)
}
func (m *DummyPreprepare) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyPreprepare.DiscardUnknown(m)
}

var xxx_messageInfo_DummyPreprepare proto.InternalMessageInfo

func (m *DummyPreprepare) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *DummyPreprepare) GetBatch() *requestpb.Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "messagepb.Message")
	proto.RegisterType((*DummyPreprepare)(nil), "messagepb.DummyPreprepare")
}

func init() { proto.RegisterFile("messagepb/messagepb.proto", fileDescriptor_5e5db85d23e1fb5b) }

var fileDescriptor_5e5db85d23e1fb5b = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0x3a, 0x27, 0x46, 0x70, 0x5b, 0x4e, 0x5d, 0x4f, 0x32, 0x50, 0xbc, 0x98, 0x80,
	0xc3, 0x2f, 0x50, 0x04, 0xb7, 0x83, 0x20, 0xdd, 0xcd, 0x8b, 0x34, 0xeb, 0xb3, 0x2d, 0x2e, 0xeb,
	0x33, 0x2f, 0x3d, 0xf4, 0xe8, 0x37, 0x97, 0x26, 0x92, 0xa9, 0x10, 0xc2, 0xe3, 0xf7, 0xff, 0x3d,
	0xf2, 0xf2, 0xd8, 0x42, 0x03, 0x51, 0x51, 0x01, 0x2a, 0x19, 0x2a, 0x81, 0xa6, 0xb5, 0x2d, 0x3f,
	0x0f, 0x20, 0x5d, 0x18, 0xf8, 0xec, 0x80, 0x2c, 0x2a, 0x19, 0x2a, 0x6f, 0xa5, 0xf3, 0x86, 0x08,
	0x95, 0x74, 0xb7, 0x47, 0xcb, 0xaf, 0x88, 0x9d, 0x3d, 0xfb, 0x5e, 0x7e, 0xcd, 0x4e, 0x1a, 0xa2,
	0x24, 0xba, 0x8a, 0x6e, 0x2f, 0xee, 0xe7, 0xc2, 0x6b, 0x9b, 0xed, 0xf6, 0x27, 0x5f, 0x8f, 0xf2,
	0x21, 0xe7, 0x4f, 0x6c, 0x56, 0x76, 0x5a, 0xf7, 0x6f, 0x68, 0x60, 0x38, 0x85, 0x81, 0xa4, 0x74,
	0x3d, 0xa9, 0x38, 0xce, 0xf5, 0x38, 0x28, 0x2f, 0xc1, 0x58, 0x8f, 0xf2, 0x69, 0xf9, 0x17, 0x65,
	0x13, 0x36, 0xb6, 0x3d, 0xc2, 0x72, 0xc3, 0xa6, 0xff, 0x6c, 0x7e, 0xc9, 0x62, 0x3a, 0xb8, 0x49,
	0xc6, 0x79, 0x4c, 0x07, 0x7e, 0xc3, 0x4e, 0x55, 0x61, 0x77, 0x75, 0x12, 0xbb, 0x87, 0x66, 0xe2,
	0xf8, 0xb5, 0x6c, 0xe0, 0xb9, 0x8f, 0xb3, 0x87, 0xd7, 0x55, 0xd5, 0xd8, 0xba, 0x53, 0x62, 0xd7,
	0x6a, 0x59, 0xf7, 0x08, 0x66, 0x0f, 0x65, 0x05, 0xe6, 0x6e, 0x5f, 0x28, 0x92, 0xba, 0x31, 0xea,
	0xdd, 0x4a, 0xfc, 0xa8, 0xe4, 0xef, 0x25, 0xaa, 0x89, 0x5b, 0xc6, 0xea, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x39, 0x65, 0x14, 0x1b, 0x62, 0x01, 0x00, 0x00,
}
