/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0

Refactored: 1
*/

package deploytest

import (
	"fmt"
	"github.com/hyperledger-labs/mirbft/pkg/logger"
	"github.com/hyperledger-labs/mirbft/pkg/pb/state"
	"github.com/hyperledger-labs/mirbft/pkg/statemachine"
	"github.com/hyperledger-labs/mirbft/pkg/status"
)

// DummySM is a stub for a protocol state machine implementation.
type DummySM struct {
	logger logger.Logger
}

// NewDummySM creates and returns a pointer to a new instance of DummySM.
// Log output generated by this instance will be directed to logger.
func NewDummySM(logger logger.Logger) *DummySM {
	return &DummySM{logger: logger}
}

// ApplyEvent applies an event to the state machine, deterministically advancing its state
// and generating a (possibly empty) list of output events.
func (dsm *DummySM) ApplyEvent(event *state.Event) *statemachine.EventList {
	dsm.logger.Log(logger.LevelDebug, "Ignoring event",
		"type", fmt.Sprintf("%T", event.Type))

	switch event.Type.(type) {
	case *state.Event_Message:
		dsm.logger.Log(logger.LevelDebug, "Message event.")
	case *state.Event_TickElapsed:
		dsm.logger.Log(logger.LevelDebug, "Tick elapsed.")
	default:
		panic(fmt.Sprintf("unknown state machine event type: %T", event.Type))
	}

	return &statemachine.EventList{}
}

// Status returns an empty state machine state.
func (dsm *DummySM) Status() (s *status.StateMachine, err error) {
	return &status.StateMachine{}, nil
}
