// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recorder.proto

package recorderpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mirbftpb "github.com/IBM/mirbft/mirbftpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RecordedEvent struct {
	NodeId               uint64               `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Time                 int64                `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	StateEvent           *mirbftpb.StateEvent `protobuf:"bytes,3,opt,name=state_event,json=stateEvent,proto3" json:"state_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecordedEvent) Reset()         { *m = RecordedEvent{} }
func (m *RecordedEvent) String() string { return proto.CompactTextString(m) }
func (*RecordedEvent) ProtoMessage()    {}
func (*RecordedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_recorder_3f28649113cf5f45, []int{0}
}
func (m *RecordedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordedEvent.Unmarshal(m, b)
}
func (m *RecordedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordedEvent.Marshal(b, m, deterministic)
}
func (dst *RecordedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordedEvent.Merge(dst, src)
}
func (m *RecordedEvent) XXX_Size() int {
	return xxx_messageInfo_RecordedEvent.Size(m)
}
func (m *RecordedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RecordedEvent proto.InternalMessageInfo

func (m *RecordedEvent) GetNodeId() uint64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *RecordedEvent) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RecordedEvent) GetStateEvent() *mirbftpb.StateEvent {
	if m != nil {
		return m.StateEvent
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordedEvent)(nil), "recorderpb.RecordedEvent")
}

func init() { proto.RegisterFile("recorder.proto", fileDescriptor_recorder_3f28649113cf5f45) }

var fileDescriptor_recorder_3f28649113cf5f45 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xce,
	0x2f, 0x4a, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x82, 0xf1, 0x0b, 0x92,
	0xa4, 0x44, 0x73, 0x33, 0x8b, 0x92, 0xd2, 0x4a, 0x0a, 0x92, 0xf4, 0x21, 0x0c, 0x88, 0x12, 0xa5,
	0x62, 0x2e, 0xde, 0x20, 0x88, 0xa2, 0x14, 0xd7, 0xb2, 0xd4, 0xbc, 0x12, 0x21, 0x71, 0x2e, 0xf6,
	0xbc, 0xfc, 0x94, 0xd4, 0xf8, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x36, 0x10,
	0xd7, 0x33, 0x45, 0x48, 0x88, 0x8b, 0xa5, 0x24, 0x33, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83,
	0x39, 0x08, 0xcc, 0x16, 0x32, 0xe5, 0xe2, 0x2e, 0x2e, 0x49, 0x2c, 0x49, 0x8d, 0x4f, 0x05, 0xe9,
	0x95, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd1, 0x83, 0x59, 0xa5, 0x17, 0x0c, 0x92, 0x04,
	0x9b, 0x1b, 0xc4, 0x55, 0x0c, 0x67, 0x27, 0xb1, 0x81, 0xed, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0x1a, 0xb6, 0x35, 0xb0, 0x00, 0x00, 0x00,
}
