// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mirbft.proto

package mirbftpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	// Types that are valid to be assigned to Type:
	//	*Msg_Preprepare
	//	*Msg_Prepare
	//	*Msg_Commit
	//	*Msg_Forward
	//	*Msg_Checkpoint
	//	*Msg_Suspect
	//	*Msg_EpochChange
	//	*Msg_NewEpoch
	//	*Msg_NewEpochEcho
	//	*Msg_NewEpochReady
	Type                 isMsg_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{0}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (dst *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(dst, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

type isMsg_Type interface {
	isMsg_Type()
}

type Msg_Preprepare struct {
	Preprepare *Preprepare `protobuf:"bytes,1,opt,name=preprepare,proto3,oneof"`
}

type Msg_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,2,opt,name=prepare,proto3,oneof"`
}

type Msg_Commit struct {
	Commit *Commit `protobuf:"bytes,3,opt,name=commit,proto3,oneof"`
}

type Msg_Forward struct {
	Forward *Forward `protobuf:"bytes,4,opt,name=forward,proto3,oneof"`
}

type Msg_Checkpoint struct {
	Checkpoint *Checkpoint `protobuf:"bytes,5,opt,name=checkpoint,proto3,oneof"`
}

type Msg_Suspect struct {
	Suspect *Suspect `protobuf:"bytes,6,opt,name=suspect,proto3,oneof"`
}

type Msg_EpochChange struct {
	EpochChange *EpochChange `protobuf:"bytes,7,opt,name=epoch_change,json=epochChange,proto3,oneof"`
}

type Msg_NewEpoch struct {
	NewEpoch *NewEpoch `protobuf:"bytes,8,opt,name=new_epoch,json=newEpoch,proto3,oneof"`
}

type Msg_NewEpochEcho struct {
	NewEpochEcho *NewEpochEcho `protobuf:"bytes,9,opt,name=new_epoch_echo,json=newEpochEcho,proto3,oneof"`
}

type Msg_NewEpochReady struct {
	NewEpochReady *NewEpochReady `protobuf:"bytes,10,opt,name=new_epoch_ready,json=newEpochReady,proto3,oneof"`
}

func (*Msg_Preprepare) isMsg_Type() {}

func (*Msg_Prepare) isMsg_Type() {}

func (*Msg_Commit) isMsg_Type() {}

func (*Msg_Forward) isMsg_Type() {}

func (*Msg_Checkpoint) isMsg_Type() {}

func (*Msg_Suspect) isMsg_Type() {}

func (*Msg_EpochChange) isMsg_Type() {}

func (*Msg_NewEpoch) isMsg_Type() {}

func (*Msg_NewEpochEcho) isMsg_Type() {}

func (*Msg_NewEpochReady) isMsg_Type() {}

func (m *Msg) GetType() isMsg_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Msg) GetPreprepare() *Preprepare {
	if x, ok := m.GetType().(*Msg_Preprepare); ok {
		return x.Preprepare
	}
	return nil
}

func (m *Msg) GetPrepare() *Prepare {
	if x, ok := m.GetType().(*Msg_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *Msg) GetCommit() *Commit {
	if x, ok := m.GetType().(*Msg_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Msg) GetForward() *Forward {
	if x, ok := m.GetType().(*Msg_Forward); ok {
		return x.Forward
	}
	return nil
}

func (m *Msg) GetCheckpoint() *Checkpoint {
	if x, ok := m.GetType().(*Msg_Checkpoint); ok {
		return x.Checkpoint
	}
	return nil
}

func (m *Msg) GetSuspect() *Suspect {
	if x, ok := m.GetType().(*Msg_Suspect); ok {
		return x.Suspect
	}
	return nil
}

func (m *Msg) GetEpochChange() *EpochChange {
	if x, ok := m.GetType().(*Msg_EpochChange); ok {
		return x.EpochChange
	}
	return nil
}

func (m *Msg) GetNewEpoch() *NewEpoch {
	if x, ok := m.GetType().(*Msg_NewEpoch); ok {
		return x.NewEpoch
	}
	return nil
}

func (m *Msg) GetNewEpochEcho() *NewEpochEcho {
	if x, ok := m.GetType().(*Msg_NewEpochEcho); ok {
		return x.NewEpochEcho
	}
	return nil
}

func (m *Msg) GetNewEpochReady() *NewEpochReady {
	if x, ok := m.GetType().(*Msg_NewEpochReady); ok {
		return x.NewEpochReady
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Msg) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Msg_OneofMarshaler, _Msg_OneofUnmarshaler, _Msg_OneofSizer, []interface{}{
		(*Msg_Preprepare)(nil),
		(*Msg_Prepare)(nil),
		(*Msg_Commit)(nil),
		(*Msg_Forward)(nil),
		(*Msg_Checkpoint)(nil),
		(*Msg_Suspect)(nil),
		(*Msg_EpochChange)(nil),
		(*Msg_NewEpoch)(nil),
		(*Msg_NewEpochEcho)(nil),
		(*Msg_NewEpochReady)(nil),
	}
}

func _Msg_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Msg)
	// type
	switch x := m.Type.(type) {
	case *Msg_Preprepare:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Preprepare); err != nil {
			return err
		}
	case *Msg_Prepare:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Prepare); err != nil {
			return err
		}
	case *Msg_Commit:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Commit); err != nil {
			return err
		}
	case *Msg_Forward:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Forward); err != nil {
			return err
		}
	case *Msg_Checkpoint:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Checkpoint); err != nil {
			return err
		}
	case *Msg_Suspect:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Suspect); err != nil {
			return err
		}
	case *Msg_EpochChange:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EpochChange); err != nil {
			return err
		}
	case *Msg_NewEpoch:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewEpoch); err != nil {
			return err
		}
	case *Msg_NewEpochEcho:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewEpochEcho); err != nil {
			return err
		}
	case *Msg_NewEpochReady:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewEpochReady); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Msg.Type has unexpected type %T", x)
	}
	return nil
}

func _Msg_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Msg)
	switch tag {
	case 1: // type.preprepare
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Preprepare)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_Preprepare{msg}
		return true, err
	case 2: // type.prepare
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Prepare)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_Prepare{msg}
		return true, err
	case 3: // type.commit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Commit)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_Commit{msg}
		return true, err
	case 4: // type.forward
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Forward)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_Forward{msg}
		return true, err
	case 5: // type.checkpoint
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Checkpoint)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_Checkpoint{msg}
		return true, err
	case 6: // type.suspect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Suspect)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_Suspect{msg}
		return true, err
	case 7: // type.epoch_change
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EpochChange)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_EpochChange{msg}
		return true, err
	case 8: // type.new_epoch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NewEpoch)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_NewEpoch{msg}
		return true, err
	case 9: // type.new_epoch_echo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NewEpochEcho)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_NewEpochEcho{msg}
		return true, err
	case 10: // type.new_epoch_ready
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NewEpochReady)
		err := b.DecodeMessage(msg)
		m.Type = &Msg_NewEpochReady{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Msg_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Msg)
	// type
	switch x := m.Type.(type) {
	case *Msg_Preprepare:
		s := proto.Size(x.Preprepare)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_Prepare:
		s := proto.Size(x.Prepare)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_Commit:
		s := proto.Size(x.Commit)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_Forward:
		s := proto.Size(x.Forward)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_Checkpoint:
		s := proto.Size(x.Checkpoint)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_Suspect:
		s := proto.Size(x.Suspect)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_EpochChange:
		s := proto.Size(x.EpochChange)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_NewEpoch:
		s := proto.Size(x.NewEpoch)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_NewEpochEcho:
		s := proto.Size(x.NewEpochEcho)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_NewEpochReady:
		s := proto.Size(x.NewEpochReady)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Preprepare struct {
	SeqNo                uint64   `protobuf:"varint,1,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Epoch                uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Bucket               uint64   `protobuf:"varint,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Batch                [][]byte `protobuf:"bytes,4,rep,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preprepare) Reset()         { *m = Preprepare{} }
func (m *Preprepare) String() string { return proto.CompactTextString(m) }
func (*Preprepare) ProtoMessage()    {}
func (*Preprepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{1}
}
func (m *Preprepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preprepare.Unmarshal(m, b)
}
func (m *Preprepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preprepare.Marshal(b, m, deterministic)
}
func (dst *Preprepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preprepare.Merge(dst, src)
}
func (m *Preprepare) XXX_Size() int {
	return xxx_messageInfo_Preprepare.Size(m)
}
func (m *Preprepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Preprepare.DiscardUnknown(m)
}

var xxx_messageInfo_Preprepare proto.InternalMessageInfo

func (m *Preprepare) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *Preprepare) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Preprepare) GetBucket() uint64 {
	if m != nil {
		return m.Bucket
	}
	return 0
}

func (m *Preprepare) GetBatch() [][]byte {
	if m != nil {
		return m.Batch
	}
	return nil
}

type Prepare struct {
	SeqNo                uint64   `protobuf:"varint,1,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Epoch                uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Bucket               uint64   `protobuf:"varint,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Digest               []byte   `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{2}
}
func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (dst *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(dst, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *Prepare) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Prepare) GetBucket() uint64 {
	if m != nil {
		return m.Bucket
	}
	return 0
}

func (m *Prepare) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

type Commit struct {
	SeqNo                uint64   `protobuf:"varint,1,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Epoch                uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Bucket               uint64   `protobuf:"varint,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Digest               []byte   `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{3}
}
func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (dst *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(dst, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *Commit) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Commit) GetBucket() uint64 {
	if m != nil {
		return m.Bucket
	}
	return 0
}

func (m *Commit) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

type Checkpoint struct {
	SeqNo                uint64   `protobuf:"varint,1,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{4}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (dst *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(dst, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *Checkpoint) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Forward struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Bucket               uint64   `protobuf:"varint,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Forward) Reset()         { *m = Forward{} }
func (m *Forward) String() string { return proto.CompactTextString(m) }
func (*Forward) ProtoMessage()    {}
func (*Forward) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{5}
}
func (m *Forward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Forward.Unmarshal(m, b)
}
func (m *Forward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Forward.Marshal(b, m, deterministic)
}
func (dst *Forward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Forward.Merge(dst, src)
}
func (m *Forward) XXX_Size() int {
	return xxx_messageInfo_Forward.Size(m)
}
func (m *Forward) XXX_DiscardUnknown() {
	xxx_messageInfo_Forward.DiscardUnknown(m)
}

var xxx_messageInfo_Forward proto.InternalMessageInfo

func (m *Forward) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Forward) GetBucket() uint64 {
	if m != nil {
		return m.Bucket
	}
	return 0
}

func (m *Forward) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Suspect struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suspect) Reset()         { *m = Suspect{} }
func (m *Suspect) String() string { return proto.CompactTextString(m) }
func (*Suspect) ProtoMessage()    {}
func (*Suspect) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{6}
}
func (m *Suspect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suspect.Unmarshal(m, b)
}
func (m *Suspect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suspect.Marshal(b, m, deterministic)
}
func (dst *Suspect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suspect.Merge(dst, src)
}
func (m *Suspect) XXX_Size() int {
	return xxx_messageInfo_Suspect.Size(m)
}
func (m *Suspect) XXX_DiscardUnknown() {
	xxx_messageInfo_Suspect.DiscardUnknown(m)
}

var xxx_messageInfo_Suspect proto.InternalMessageInfo

func (m *Suspect) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

// EpochChange messages are used to implement the classical PBFT view-change
// protocol, (very) slightly modified to adapt to Mir.  The assorted sets
// are encoded as repeated fields, rather than as maps for ease of serialization
// and particularly for computing a digest to attest to.  If any set contains
// a duplicated entry, the message may be discarded as byzantine.
type EpochChange struct {
	// attestation should be a signature covering the remainder of the fields
	// in the message.  additional information may optionally be encoded in the
	// attestation.
	Attestation []byte `protobuf:"bytes,1,opt,name=attestation,proto3" json:"attestation,omitempty"`
	NewEpoch    uint64 `protobuf:"varint,2,opt,name=new_epoch,json=newEpoch,proto3" json:"new_epoch,omitempty"`
	// c_set contains the entries for the C-set as defined by the classical
	// PBFT view-change protocol.
	Checkpoints []*Checkpoint `protobuf:"bytes,3,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	// p_set contains the entries for the P-set as defined by the classical
	// PBFT view-change protocol.
	PSet []*EpochChange_SetEntry `protobuf:"bytes,4,rep,name=p_set,json=pSet,proto3" json:"p_set,omitempty"`
	// q_set contains the entries for the Q-set as defined by the classical
	// PBFT view-change protocol.
	QSet                 []*EpochChange_SetEntry `protobuf:"bytes,5,rep,name=q_set,json=qSet,proto3" json:"q_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EpochChange) Reset()         { *m = EpochChange{} }
func (m *EpochChange) String() string { return proto.CompactTextString(m) }
func (*EpochChange) ProtoMessage()    {}
func (*EpochChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{7}
}
func (m *EpochChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochChange.Unmarshal(m, b)
}
func (m *EpochChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochChange.Marshal(b, m, deterministic)
}
func (dst *EpochChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochChange.Merge(dst, src)
}
func (m *EpochChange) XXX_Size() int {
	return xxx_messageInfo_EpochChange.Size(m)
}
func (m *EpochChange) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochChange.DiscardUnknown(m)
}

var xxx_messageInfo_EpochChange proto.InternalMessageInfo

func (m *EpochChange) GetAttestation() []byte {
	if m != nil {
		return m.Attestation
	}
	return nil
}

func (m *EpochChange) GetNewEpoch() uint64 {
	if m != nil {
		return m.NewEpoch
	}
	return 0
}

func (m *EpochChange) GetCheckpoints() []*Checkpoint {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

func (m *EpochChange) GetPSet() []*EpochChange_SetEntry {
	if m != nil {
		return m.PSet
	}
	return nil
}

func (m *EpochChange) GetQSet() []*EpochChange_SetEntry {
	if m != nil {
		return m.QSet
	}
	return nil
}

type EpochChange_SetEntry struct {
	Bucket               uint64   `protobuf:"varint,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Epoch                uint64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SeqNo                uint64   `protobuf:"varint,3,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Digest               []byte   `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochChange_SetEntry) Reset()         { *m = EpochChange_SetEntry{} }
func (m *EpochChange_SetEntry) String() string { return proto.CompactTextString(m) }
func (*EpochChange_SetEntry) ProtoMessage()    {}
func (*EpochChange_SetEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{7, 0}
}
func (m *EpochChange_SetEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochChange_SetEntry.Unmarshal(m, b)
}
func (m *EpochChange_SetEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochChange_SetEntry.Marshal(b, m, deterministic)
}
func (dst *EpochChange_SetEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochChange_SetEntry.Merge(dst, src)
}
func (m *EpochChange_SetEntry) XXX_Size() int {
	return xxx_messageInfo_EpochChange_SetEntry.Size(m)
}
func (m *EpochChange_SetEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochChange_SetEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EpochChange_SetEntry proto.InternalMessageInfo

func (m *EpochChange_SetEntry) GetBucket() uint64 {
	if m != nil {
		return m.Bucket
	}
	return 0
}

func (m *EpochChange_SetEntry) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochChange_SetEntry) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *EpochChange_SetEntry) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

type EpochConfig struct {
	// number of this new epoch
	Number             uint64      `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	StartingCheckpoint *Checkpoint `protobuf:"bytes,2,opt,name=starting_checkpoint,json=startingCheckpoint,proto3" json:"starting_checkpoint,omitempty"`
	Leaders            []uint64    `protobuf:"varint,3,rep,packed,name=leaders,proto3" json:"leaders,omitempty"`
	// final_preprepares finalizes the last checkpoint window or windows
	// which some correct replica preprepared a sequence in.  Notably
	// the bucket configuration is derived from the last active epoch.
	// By active epoch, we mean any epoch for which some correct replica
	// prepared a request.
	FinalPreprepares     []*EpochConfig_Bucket `protobuf:"bytes,4,rep,name=final_preprepares,json=finalPreprepares,proto3" json:"final_preprepares,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EpochConfig) Reset()         { *m = EpochConfig{} }
func (m *EpochConfig) String() string { return proto.CompactTextString(m) }
func (*EpochConfig) ProtoMessage()    {}
func (*EpochConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{8}
}
func (m *EpochConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochConfig.Unmarshal(m, b)
}
func (m *EpochConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochConfig.Marshal(b, m, deterministic)
}
func (dst *EpochConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochConfig.Merge(dst, src)
}
func (m *EpochConfig) XXX_Size() int {
	return xxx_messageInfo_EpochConfig.Size(m)
}
func (m *EpochConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EpochConfig proto.InternalMessageInfo

func (m *EpochConfig) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *EpochConfig) GetStartingCheckpoint() *Checkpoint {
	if m != nil {
		return m.StartingCheckpoint
	}
	return nil
}

func (m *EpochConfig) GetLeaders() []uint64 {
	if m != nil {
		return m.Leaders
	}
	return nil
}

func (m *EpochConfig) GetFinalPreprepares() []*EpochConfig_Bucket {
	if m != nil {
		return m.FinalPreprepares
	}
	return nil
}

type EpochConfig_Bucket struct {
	// digests is indexed by sequence number offset by the
	// starting_checkpoint seq_no. An empty digest corresponds
	// to a null request.
	Digests              [][]byte `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochConfig_Bucket) Reset()         { *m = EpochConfig_Bucket{} }
func (m *EpochConfig_Bucket) String() string { return proto.CompactTextString(m) }
func (*EpochConfig_Bucket) ProtoMessage()    {}
func (*EpochConfig_Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{8, 0}
}
func (m *EpochConfig_Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochConfig_Bucket.Unmarshal(m, b)
}
func (m *EpochConfig_Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochConfig_Bucket.Marshal(b, m, deterministic)
}
func (dst *EpochConfig_Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochConfig_Bucket.Merge(dst, src)
}
func (m *EpochConfig_Bucket) XXX_Size() int {
	return xxx_messageInfo_EpochConfig_Bucket.Size(m)
}
func (m *EpochConfig_Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochConfig_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_EpochConfig_Bucket proto.InternalMessageInfo

func (m *EpochConfig_Bucket) GetDigests() [][]byte {
	if m != nil {
		return m.Digests
	}
	return nil
}

// NewEpoch is akin to the NewView message in classical PBFT and follows the same
// semantics.  Optionally, for graceful epoch change, the epoch_changes field may
// be empty.  In the event that the previous epoch does not complete gracefully,
// the graceful NewEpoch is ignored.  Unlike in classical PBFT, we employ a classical
// Bracha reliable broadcast on embedded config.  A replica should respond to a NewEpoch
// message with a NewEpochEcho (assuming that the NewEpoch message is validly constructed).
type NewEpoch struct {
	Config *EpochConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// epoch_changes must contains at least 2f+1 EpochChange messages from
	// replicas in the network.  If two EpochChanges originated from the same
	// replica, then the NewEpoch message is invalid.
	EpochChanges         []*NewEpoch_RemoteEpochChange `protobuf:"bytes,2,rep,name=epoch_changes,json=epochChanges,proto3" json:"epoch_changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *NewEpoch) Reset()         { *m = NewEpoch{} }
func (m *NewEpoch) String() string { return proto.CompactTextString(m) }
func (*NewEpoch) ProtoMessage()    {}
func (*NewEpoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{9}
}
func (m *NewEpoch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEpoch.Unmarshal(m, b)
}
func (m *NewEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEpoch.Marshal(b, m, deterministic)
}
func (dst *NewEpoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEpoch.Merge(dst, src)
}
func (m *NewEpoch) XXX_Size() int {
	return xxx_messageInfo_NewEpoch.Size(m)
}
func (m *NewEpoch) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEpoch.DiscardUnknown(m)
}

var xxx_messageInfo_NewEpoch proto.InternalMessageInfo

func (m *NewEpoch) GetConfig() *EpochConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *NewEpoch) GetEpochChanges() []*NewEpoch_RemoteEpochChange {
	if m != nil {
		return m.EpochChanges
	}
	return nil
}

type NewEpoch_RemoteEpochChange struct {
	NodeId               uint64       `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EpochChange          *EpochChange `protobuf:"bytes,2,opt,name=epoch_change,json=epochChange,proto3" json:"epoch_change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewEpoch_RemoteEpochChange) Reset()         { *m = NewEpoch_RemoteEpochChange{} }
func (m *NewEpoch_RemoteEpochChange) String() string { return proto.CompactTextString(m) }
func (*NewEpoch_RemoteEpochChange) ProtoMessage()    {}
func (*NewEpoch_RemoteEpochChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{9, 0}
}
func (m *NewEpoch_RemoteEpochChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEpoch_RemoteEpochChange.Unmarshal(m, b)
}
func (m *NewEpoch_RemoteEpochChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEpoch_RemoteEpochChange.Marshal(b, m, deterministic)
}
func (dst *NewEpoch_RemoteEpochChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEpoch_RemoteEpochChange.Merge(dst, src)
}
func (m *NewEpoch_RemoteEpochChange) XXX_Size() int {
	return xxx_messageInfo_NewEpoch_RemoteEpochChange.Size(m)
}
func (m *NewEpoch_RemoteEpochChange) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEpoch_RemoteEpochChange.DiscardUnknown(m)
}

var xxx_messageInfo_NewEpoch_RemoteEpochChange proto.InternalMessageInfo

func (m *NewEpoch_RemoteEpochChange) GetNodeId() uint64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *NewEpoch_RemoteEpochChange) GetEpochChange() *EpochChange {
	if m != nil {
		return m.EpochChange
	}
	return nil
}

// NewEpochReady is for the second round of the classical Bracha reliable broadcast.  Note,
// that the message embeds only the config.  This is because the config is derived from
// the epoch_changes, and a correct replica will only echo the request if the config is validly
// constructed.  Since the echo phase only proceeds to ready if 2f+1 echos occur, some (actually, f+1)
// correct replicas must have validated the new config according to the epoch_changes.
type NewEpochEcho struct {
	Config               *EpochConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewEpochEcho) Reset()         { *m = NewEpochEcho{} }
func (m *NewEpochEcho) String() string { return proto.CompactTextString(m) }
func (*NewEpochEcho) ProtoMessage()    {}
func (*NewEpochEcho) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{10}
}
func (m *NewEpochEcho) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEpochEcho.Unmarshal(m, b)
}
func (m *NewEpochEcho) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEpochEcho.Marshal(b, m, deterministic)
}
func (dst *NewEpochEcho) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEpochEcho.Merge(dst, src)
}
func (m *NewEpochEcho) XXX_Size() int {
	return xxx_messageInfo_NewEpochEcho.Size(m)
}
func (m *NewEpochEcho) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEpochEcho.DiscardUnknown(m)
}

var xxx_messageInfo_NewEpochEcho proto.InternalMessageInfo

func (m *NewEpochEcho) GetConfig() *EpochConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// NewEpochReady is for the final round fo the classical Bracha reliable broadcast.
type NewEpochReady struct {
	Config               *EpochConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewEpochReady) Reset()         { *m = NewEpochReady{} }
func (m *NewEpochReady) String() string { return proto.CompactTextString(m) }
func (*NewEpochReady) ProtoMessage()    {}
func (*NewEpochReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_mirbft_98890a7fd814987b, []int{11}
}
func (m *NewEpochReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEpochReady.Unmarshal(m, b)
}
func (m *NewEpochReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEpochReady.Marshal(b, m, deterministic)
}
func (dst *NewEpochReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEpochReady.Merge(dst, src)
}
func (m *NewEpochReady) XXX_Size() int {
	return xxx_messageInfo_NewEpochReady.Size(m)
}
func (m *NewEpochReady) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEpochReady.DiscardUnknown(m)
}

var xxx_messageInfo_NewEpochReady proto.InternalMessageInfo

func (m *NewEpochReady) GetConfig() *EpochConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg)(nil), "mirbftpb.Msg")
	proto.RegisterType((*Preprepare)(nil), "mirbftpb.Preprepare")
	proto.RegisterType((*Prepare)(nil), "mirbftpb.Prepare")
	proto.RegisterType((*Commit)(nil), "mirbftpb.Commit")
	proto.RegisterType((*Checkpoint)(nil), "mirbftpb.Checkpoint")
	proto.RegisterType((*Forward)(nil), "mirbftpb.Forward")
	proto.RegisterType((*Suspect)(nil), "mirbftpb.Suspect")
	proto.RegisterType((*EpochChange)(nil), "mirbftpb.EpochChange")
	proto.RegisterType((*EpochChange_SetEntry)(nil), "mirbftpb.EpochChange.SetEntry")
	proto.RegisterType((*EpochConfig)(nil), "mirbftpb.EpochConfig")
	proto.RegisterType((*EpochConfig_Bucket)(nil), "mirbftpb.EpochConfig.Bucket")
	proto.RegisterType((*NewEpoch)(nil), "mirbftpb.NewEpoch")
	proto.RegisterType((*NewEpoch_RemoteEpochChange)(nil), "mirbftpb.NewEpoch.RemoteEpochChange")
	proto.RegisterType((*NewEpochEcho)(nil), "mirbftpb.NewEpochEcho")
	proto.RegisterType((*NewEpochReady)(nil), "mirbftpb.NewEpochReady")
}

func init() { proto.RegisterFile("mirbft.proto", fileDescriptor_mirbft_98890a7fd814987b) }

var fileDescriptor_mirbft_98890a7fd814987b = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6a, 0xdb, 0x48,
	0x14, 0xf6, 0x8f, 0x2c, 0x3b, 0xc7, 0xca, 0x6e, 0x32, 0x9b, 0x1f, 0x91, 0x5d, 0x76, 0x8d, 0xd8,
	0x8b, 0xb0, 0x10, 0xc3, 0x26, 0x10, 0xda, 0x42, 0x03, 0x4d, 0x70, 0x71, 0x28, 0x0d, 0x61, 0xfc,
	0x00, 0x42, 0x96, 0x8e, 0x6d, 0x91, 0x58, 0x23, 0x6b, 0xc6, 0x0d, 0x79, 0xa3, 0xbe, 0x51, 0x5f,
	0xa2, 0xb7, 0xbd, 0x2f, 0x33, 0x23, 0x59, 0xe3, 0x9f, 0x84, 0x06, 0x5a, 0xf0, 0x85, 0xcf, 0x9c,
	0xef, 0x3b, 0xe7, 0xcc, 0xcc, 0x37, 0x9f, 0xc0, 0x99, 0xc6, 0xd9, 0x70, 0x24, 0xba, 0x69, 0xc6,
	0x04, 0x23, 0x2d, 0x1d, 0xa5, 0x43, 0xef, 0xb3, 0x05, 0xf5, 0x8f, 0x7c, 0x4c, 0xce, 0x01, 0xd2,
	0x0c, 0xe5, 0x2f, 0xc8, 0xd0, 0xad, 0x76, 0xaa, 0xc7, 0xed, 0xd3, 0xbd, 0x6e, 0x01, 0xeb, 0xde,
	0x2e, 0x72, 0xfd, 0x0a, 0x35, 0x90, 0xe4, 0x04, 0x9a, 0x05, 0xa9, 0xa6, 0x48, 0xbb, 0xcb, 0x24,
	0xcd, 0x28, 0x30, 0xe4, 0x3f, 0xb0, 0x43, 0x36, 0x9d, 0xc6, 0xc2, 0xad, 0x2b, 0xf4, 0x4e, 0x89,
	0xbe, 0x52, 0xeb, 0xfd, 0x0a, 0xcd, 0x11, 0xb2, 0xf4, 0x88, 0x65, 0x0f, 0x41, 0x16, 0xb9, 0xd6,
	0x6a, 0xe9, 0xf7, 0x3a, 0x21, 0x4b, 0xe7, 0x18, 0xb9, 0x83, 0x70, 0x82, 0xe1, 0x5d, 0xca, 0xe2,
	0x44, 0xb8, 0x8d, 0xd5, 0x1d, 0x5c, 0x2d, 0x72, 0x72, 0x07, 0x25, 0x52, 0xb6, 0xe1, 0x73, 0x9e,
	0x62, 0x28, 0x5c, 0x7b, 0xb5, 0xcd, 0x40, 0x27, 0x64, 0x9b, 0x1c, 0x43, 0xde, 0x80, 0x83, 0x29,
	0x0b, 0x27, 0x7e, 0x38, 0x09, 0x92, 0x31, 0xba, 0x4d, 0xc5, 0xd9, 0x2f, 0x39, 0x3d, 0x99, 0xbd,
	0x52, 0xc9, 0x7e, 0x85, 0xb6, 0xb1, 0x0c, 0xc9, 0xff, 0xb0, 0x95, 0xe0, 0x83, 0xaf, 0x96, 0xdc,
	0x96, 0x22, 0x92, 0x92, 0x78, 0x83, 0x0f, 0x8a, 0xdb, 0xaf, 0xd0, 0x56, 0x92, 0xff, 0x27, 0x17,
	0xf0, 0xdb, 0x82, 0xe2, 0x63, 0x38, 0x61, 0xee, 0x96, 0xe2, 0x1d, 0xac, 0xf3, 0x7a, 0xe1, 0x84,
	0xf5, 0x2b, 0xd4, 0x49, 0x8c, 0x98, 0xbc, 0x83, 0xdf, 0x4b, 0x7e, 0x86, 0x41, 0xf4, 0xe8, 0x82,
	0x2a, 0x70, 0xb8, 0x5e, 0x80, 0xca, 0x74, 0xbf, 0x42, 0xb7, 0x13, 0x73, 0xe1, 0xd2, 0x06, 0x4b,
	0x3c, 0xa6, 0xe8, 0x8d, 0x01, 0x4a, 0x19, 0x90, 0x7d, 0xb0, 0x39, 0xce, 0xfc, 0x84, 0x29, 0xb1,
	0x58, 0xb4, 0xc1, 0x71, 0x76, 0xc3, 0xc8, 0x1e, 0x34, 0xf4, 0xf6, 0x6a, 0x7a, 0x55, 0x05, 0xe4,
	0x00, 0xec, 0xe1, 0x3c, 0xbc, 0x43, 0x7d, 0xed, 0x16, 0xcd, 0x23, 0x89, 0x1e, 0x06, 0x22, 0x9c,
	0xb8, 0x56, 0xa7, 0x7e, 0xec, 0x50, 0x1d, 0x78, 0x23, 0x68, 0xde, 0xfe, 0xcc, 0x2e, 0x07, 0x60,
	0x47, 0xf1, 0x18, 0xb9, 0x50, 0x3a, 0x72, 0x68, 0x1e, 0x79, 0x08, 0xb6, 0x16, 0xdd, 0xaf, 0x6d,
	0xf3, 0x1a, 0xa0, 0x14, 0xdf, 0x33, 0xad, 0x3e, 0x05, 0xf7, 0x73, 0xfd, 0x8a, 0x1c, 0xaa, 0x03,
	0xef, 0x03, 0x34, 0x73, 0xa5, 0x97, 0xb3, 0x54, 0x37, 0xcf, 0x52, 0x5b, 0x9a, 0x85, 0x80, 0x15,
	0x05, 0x22, 0x50, 0x13, 0x3a, 0x54, 0xfd, 0xf7, 0xfe, 0x81, 0x66, 0xae, 0xe7, 0xcd, 0xc5, 0xbc,
	0x2f, 0x35, 0x68, 0x1b, 0xea, 0x25, 0x1d, 0x68, 0x07, 0x42, 0x20, 0x17, 0x81, 0x88, 0x59, 0xa2,
	0xb0, 0x0e, 0x35, 0x97, 0xc8, 0x9f, 0xa6, 0xa0, 0xf5, 0x04, 0xa5, 0x74, 0xcf, 0xa1, 0x5d, 0x3e,
	0x33, 0xee, 0xd6, 0x3b, 0xf5, 0xa7, 0x5e, 0x24, 0x35, 0x81, 0xe4, 0x0c, 0x1a, 0xa9, 0xcf, 0x51,
	0x28, 0x51, 0xb4, 0x4f, 0xff, 0xde, 0xf8, 0xb4, 0xba, 0x03, 0x14, 0xbd, 0x44, 0x64, 0x8f, 0xd4,
	0x4a, 0x07, 0x28, 0x24, 0x69, 0xa6, 0x48, 0x8d, 0x1f, 0x23, 0xcd, 0x06, 0x28, 0x8e, 0xc6, 0xd0,
	0x2a, 0x56, 0x8c, 0x93, 0xac, 0xae, 0x4a, 0x74, 0x83, 0x06, 0xca, 0x5b, 0xac, 0x9b, 0xb7, 0xf8,
	0x94, 0x04, 0xbe, 0x55, 0x8b, 0x93, 0x65, 0xc9, 0x28, 0x1e, 0x4b, 0x5c, 0x32, 0x9f, 0x0e, 0x31,
	0x2b, 0x9a, 0xe9, 0x88, 0xf4, 0xe0, 0x0f, 0x2e, 0x82, 0x4c, 0xc4, 0xc9, 0xd8, 0x37, 0xcc, 0xac,
	0xf6, 0xb4, 0x99, 0x51, 0x52, 0x10, 0x0c, 0x8d, 0xb9, 0xd0, 0xbc, 0xc7, 0x20, 0xc2, 0x4c, 0x9f,
	0xba, 0x45, 0x8b, 0x90, 0x5c, 0xc3, 0xee, 0x28, 0x4e, 0x82, 0x7b, 0xbf, 0xb4, 0x70, 0x9e, 0x9f,
	0xf3, 0x5f, 0xab, 0x47, 0xa6, 0x46, 0xed, 0x5e, 0xaa, 0x63, 0xa0, 0x3b, 0x8a, 0x56, 0xbe, 0x7f,
	0x7e, 0xe4, 0x81, 0xad, 0x73, 0xb2, 0x9d, 0xde, 0x27, 0x77, 0xab, 0xea, 0x1d, 0x17, 0xa1, 0xf7,
	0xb5, 0x0a, 0xad, 0xc2, 0x5d, 0xc8, 0x89, 0xf4, 0x7e, 0x59, 0x33, 0xff, 0xbc, 0xec, 0x6f, 0x6c,
	0x48, 0x73, 0x10, 0xb9, 0x86, 0x6d, 0xd3, 0x68, 0xb9, 0x5b, 0x53, 0x63, 0xfe, 0xbb, 0xee, 0x5b,
	0x5d, 0x8a, 0x53, 0x26, 0xd0, 0xb8, 0x68, 0xea, 0x18, 0xb6, 0xcb, 0x8f, 0x46, 0xb0, 0xbb, 0x06,
	0x21, 0x87, 0xd0, 0x4c, 0x58, 0x84, 0x7e, 0x1c, 0x2d, 0x2e, 0x81, 0x45, 0x78, 0x1d, 0x91, 0x57,
	0x2b, 0x0e, 0x5f, 0x7b, 0xc6, 0xe1, 0x97, 0xfc, 0xdd, 0x7b, 0x0b, 0x8e, 0x69, 0xc6, 0x2f, 0xdc,
	0xb1, 0x77, 0x01, 0xdb, 0x4b, 0x56, 0xfc, 0x42, 0xfe, 0xd0, 0x56, 0x1f, 0xf7, 0xb3, 0xef, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x40, 0x1b, 0x48, 0xab, 0xec, 0x07, 0x00, 0x00,
}
