//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: grpctransport/grpctransport.proto

package grpctransport

import (
	context "context"
	messagepb "github.com/hyperledger-labs/mirbft/pkg/pb/messagepb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender uint64             `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Msg    *messagepb.Message `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GrpcMessage) Reset() {
	*x = GrpcMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctransport_grpctransport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMessage) ProtoMessage() {}

func (x *GrpcMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpctransport_grpctransport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMessage.ProtoReflect.Descriptor instead.
func (*GrpcMessage) Descriptor() ([]byte, []int) {
	return file_grpctransport_grpctransport_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcMessage) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *GrpcMessage) GetMsg() *messagepb.Message {
	if x != nil {
		return x.Msg
	}
	return nil
}

type ByeBye struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ByeBye) Reset() {
	*x = ByeBye{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctransport_grpctransport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByeBye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByeBye) ProtoMessage() {}

func (x *ByeBye) ProtoReflect() protoreflect.Message {
	mi := &file_grpctransport_grpctransport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByeBye.ProtoReflect.Descriptor instead.
func (*ByeBye) Descriptor() ([]byte, []int) {
	return file_grpctransport_grpctransport_proto_rawDescGZIP(), []int{1}
}

var File_grpctransport_grpctransport_proto protoreflect.FileDescriptor

var file_grpctransport_grpctransport_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x72, 0x70, 0x63, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x1a, 0x19, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a,
	0x0b, 0x47, 0x72, 0x70, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x08, 0x0a, 0x06, 0x42, 0x79,
	0x65, 0x42, 0x79, 0x65, 0x32, 0x4e, 0x0a, 0x0d, 0x47, 0x72, 0x70, 0x63, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x3d, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x12,
	0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x47, 0x72, 0x70, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x42, 0x79, 0x65, 0x42,
	0x79, 0x65, 0x28, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2d, 0x6c,
	0x61, 0x62, 0x73, 0x2f, 0x6d, 0x69, 0x72, 0x62, 0x66, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpctransport_grpctransport_proto_rawDescOnce sync.Once
	file_grpctransport_grpctransport_proto_rawDescData = file_grpctransport_grpctransport_proto_rawDesc
)

func file_grpctransport_grpctransport_proto_rawDescGZIP() []byte {
	file_grpctransport_grpctransport_proto_rawDescOnce.Do(func() {
		file_grpctransport_grpctransport_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpctransport_grpctransport_proto_rawDescData)
	})
	return file_grpctransport_grpctransport_proto_rawDescData
}

var file_grpctransport_grpctransport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpctransport_grpctransport_proto_goTypes = []interface{}{
	(*GrpcMessage)(nil),       // 0: grpctransport.GrpcMessage
	(*ByeBye)(nil),            // 1: grpctransport.ByeBye
	(*messagepb.Message)(nil), // 2: messagepb.Message
}
var file_grpctransport_grpctransport_proto_depIdxs = []int32{
	2, // 0: grpctransport.GrpcMessage.msg:type_name -> messagepb.Message
	0, // 1: grpctransport.GrpcTransport.Listen:input_type -> grpctransport.GrpcMessage
	1, // 2: grpctransport.GrpcTransport.Listen:output_type -> grpctransport.ByeBye
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpctransport_grpctransport_proto_init() }
func file_grpctransport_grpctransport_proto_init() {
	if File_grpctransport_grpctransport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpctransport_grpctransport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctransport_grpctransport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByeBye); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpctransport_grpctransport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpctransport_grpctransport_proto_goTypes,
		DependencyIndexes: file_grpctransport_grpctransport_proto_depIdxs,
		MessageInfos:      file_grpctransport_grpctransport_proto_msgTypes,
	}.Build()
	File_grpctransport_grpctransport_proto = out.File
	file_grpctransport_grpctransport_proto_rawDesc = nil
	file_grpctransport_grpctransport_proto_goTypes = nil
	file_grpctransport_grpctransport_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcTransportClient is the client API for GrpcTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcTransportClient interface {
	Listen(ctx context.Context, opts ...grpc.CallOption) (GrpcTransport_ListenClient, error)
}

type grpcTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcTransportClient(cc grpc.ClientConnInterface) GrpcTransportClient {
	return &grpcTransportClient{cc}
}

func (c *grpcTransportClient) Listen(ctx context.Context, opts ...grpc.CallOption) (GrpcTransport_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GrpcTransport_serviceDesc.Streams[0], "/grpctransport.GrpcTransport/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcTransportListenClient{stream}
	return x, nil
}

type GrpcTransport_ListenClient interface {
	Send(*GrpcMessage) error
	CloseAndRecv() (*ByeBye, error)
	grpc.ClientStream
}

type grpcTransportListenClient struct {
	grpc.ClientStream
}

func (x *grpcTransportListenClient) Send(m *GrpcMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcTransportListenClient) CloseAndRecv() (*ByeBye, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ByeBye)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcTransportServer is the server API for GrpcTransport service.
type GrpcTransportServer interface {
	Listen(GrpcTransport_ListenServer) error
}

// UnimplementedGrpcTransportServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcTransportServer struct {
}

func (*UnimplementedGrpcTransportServer) Listen(GrpcTransport_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}

func RegisterGrpcTransportServer(s *grpc.Server, srv GrpcTransportServer) {
	s.RegisterService(&_GrpcTransport_serviceDesc, srv)
}

func _GrpcTransport_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcTransportServer).Listen(&grpcTransportListenServer{stream})
}

type GrpcTransport_ListenServer interface {
	SendAndClose(*ByeBye) error
	Recv() (*GrpcMessage, error)
	grpc.ServerStream
}

type grpcTransportListenServer struct {
	grpc.ServerStream
}

func (x *grpcTransportListenServer) SendAndClose(m *ByeBye) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcTransportListenServer) Recv() (*GrpcMessage, error) {
	m := new(GrpcMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GrpcTransport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpctransport.GrpcTransport",
	HandlerType: (*GrpcTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _GrpcTransport_Listen_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpctransport/grpctransport.proto",
}
