// Code generated by protoc-gen-go. DO NOT EDIT.
// source: statuspb/statuspb.proto

package statuspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	isspb "github.com/hyperledger-labs/mirbft/pkg/pb/isspb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeStatus struct {
	Protocol             *ProtocolStatus      `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ClientTracker        *ClientTrackerStatus `protobuf:"bytes,2,opt,name=client_tracker,json=clientTracker,proto3" json:"client_tracker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NodeStatus) Reset()         { *m = NodeStatus{} }
func (m *NodeStatus) String() string { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()    {}
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_64cf36d54cdce33a, []int{0}
}

func (m *NodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatus.Unmarshal(m, b)
}
func (m *NodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatus.Marshal(b, m, deterministic)
}
func (m *NodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatus.Merge(m, src)
}
func (m *NodeStatus) XXX_Size() int {
	return xxx_messageInfo_NodeStatus.Size(m)
}
func (m *NodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatus proto.InternalMessageInfo

func (m *NodeStatus) GetProtocol() *ProtocolStatus {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (m *NodeStatus) GetClientTracker() *ClientTrackerStatus {
	if m != nil {
		return m.ClientTracker
	}
	return nil
}

type ProtocolStatus struct {
	// Types that are valid to be assigned to Type:
	//	*ProtocolStatus_Iss
	Type                 isProtocolStatus_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtocolStatus) Reset()         { *m = ProtocolStatus{} }
func (m *ProtocolStatus) String() string { return proto.CompactTextString(m) }
func (*ProtocolStatus) ProtoMessage()    {}
func (*ProtocolStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_64cf36d54cdce33a, []int{1}
}

func (m *ProtocolStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolStatus.Unmarshal(m, b)
}
func (m *ProtocolStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolStatus.Marshal(b, m, deterministic)
}
func (m *ProtocolStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolStatus.Merge(m, src)
}
func (m *ProtocolStatus) XXX_Size() int {
	return xxx_messageInfo_ProtocolStatus.Size(m)
}
func (m *ProtocolStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolStatus proto.InternalMessageInfo

type isProtocolStatus_Type interface {
	isProtocolStatus_Type()
}

type ProtocolStatus_Iss struct {
	Iss *isspb.Status `protobuf:"bytes,1,opt,name=iss,proto3,oneof"`
}

func (*ProtocolStatus_Iss) isProtocolStatus_Type() {}

func (m *ProtocolStatus) GetType() isProtocolStatus_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ProtocolStatus) GetIss() *isspb.Status {
	if x, ok := m.GetType().(*ProtocolStatus_Iss); ok {
		return x.Iss
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProtocolStatus) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProtocolStatus_Iss)(nil),
	}
}

type ClientTrackerStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientTrackerStatus) Reset()         { *m = ClientTrackerStatus{} }
func (m *ClientTrackerStatus) String() string { return proto.CompactTextString(m) }
func (*ClientTrackerStatus) ProtoMessage()    {}
func (*ClientTrackerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_64cf36d54cdce33a, []int{2}
}

func (m *ClientTrackerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientTrackerStatus.Unmarshal(m, b)
}
func (m *ClientTrackerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientTrackerStatus.Marshal(b, m, deterministic)
}
func (m *ClientTrackerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientTrackerStatus.Merge(m, src)
}
func (m *ClientTrackerStatus) XXX_Size() int {
	return xxx_messageInfo_ClientTrackerStatus.Size(m)
}
func (m *ClientTrackerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientTrackerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ClientTrackerStatus proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NodeStatus)(nil), "statuspb.NodeStatus")
	proto.RegisterType((*ProtocolStatus)(nil), "statuspb.ProtocolStatus")
	proto.RegisterType((*ClientTrackerStatus)(nil), "statuspb.ClientTrackerStatus")
}

func init() { proto.RegisterFile("statuspb/statuspb.proto", fileDescriptor_64cf36d54cdce33a) }

var fileDescriptor_64cf36d54cdce33a = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0x2e, 0x48, 0xd2, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x7c, 0x29, 0xc1, 0xcc, 0x62, 0x90, 0x3c, 0x98, 0x84, 0x48, 0x2a, 0x75, 0x30, 0x72, 0x71, 0xf9,
	0xe5, 0xa7, 0xa4, 0x06, 0x83, 0xd5, 0x08, 0x99, 0x70, 0x71, 0x80, 0xc5, 0x93, 0xf3, 0x73, 0x24,
	0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x24, 0xf4, 0xe0, 0xc6, 0x05, 0x40, 0x65, 0x20, 0x6a, 0x83,
	0xe0, 0x2a, 0x85, 0x5c, 0xb8, 0xf8, 0x92, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0xe2, 0x4b, 0x8a, 0x12,
	0x93, 0xb3, 0x53, 0x8b, 0x24, 0x98, 0xc0, 0x7a, 0x65, 0x11, 0x7a, 0x9d, 0xc1, 0xf2, 0x21, 0x10,
	0x69, 0xa8, 0x01, 0xbc, 0xc9, 0xc8, 0x82, 0x4a, 0xd6, 0x5c, 0x7c, 0xa8, 0x36, 0x08, 0x29, 0x72,
	0x31, 0x67, 0x16, 0x17, 0x43, 0x1d, 0xc2, 0xab, 0x07, 0x71, 0x37, 0x44, 0xce, 0x83, 0x21, 0x08,
	0x24, 0xe7, 0xc4, 0xc6, 0xc5, 0x52, 0x52, 0x59, 0x90, 0xaa, 0x24, 0xca, 0x25, 0x8c, 0xc5, 0x0a,
	0x27, 0x93, 0x28, 0xa3, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0x8c,
	0xca, 0x82, 0xd4, 0xa2, 0x9c, 0xd4, 0x94, 0xf4, 0xd4, 0x22, 0xdd, 0x9c, 0xc4, 0xa4, 0x62, 0xfd,
	0xdc, 0xcc, 0xa2, 0xa4, 0xb4, 0x12, 0xfd, 0x82, 0xec, 0x74, 0x7d, 0xa4, 0x70, 0x4b, 0x62, 0x03,
	0xfb, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x86, 0x7d, 0x02, 0x53, 0x01, 0x00, 0x00,
}
