// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotstufforderer.proto

package protobufs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HotStuffNode struct {
	Height               int32       `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	View                 int32       `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Parent               []byte      `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Batch                *Batch      `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	Certificate          *HotStuffQC `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Aborted              bool        `protobuf:"varint,6,opt,name=aborted,proto3" json:"aborted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HotStuffNode) Reset()         { *m = HotStuffNode{} }
func (m *HotStuffNode) String() string { return proto.CompactTextString(m) }
func (*HotStuffNode) ProtoMessage()    {}
func (*HotStuffNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc32763174c5d02, []int{0}
}

func (m *HotStuffNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotStuffNode.Unmarshal(m, b)
}
func (m *HotStuffNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotStuffNode.Marshal(b, m, deterministic)
}
func (m *HotStuffNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotStuffNode.Merge(m, src)
}
func (m *HotStuffNode) XXX_Size() int {
	return xxx_messageInfo_HotStuffNode.Size(m)
}
func (m *HotStuffNode) XXX_DiscardUnknown() {
	xxx_messageInfo_HotStuffNode.DiscardUnknown(m)
}

var xxx_messageInfo_HotStuffNode proto.InternalMessageInfo

func (m *HotStuffNode) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HotStuffNode) GetView() int32 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *HotStuffNode) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *HotStuffNode) GetBatch() *Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *HotStuffNode) GetCertificate() *HotStuffQC {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *HotStuffNode) GetAborted() bool {
	if m != nil {
		return m.Aborted
	}
	return false
}

// Since we keep a fixed leader for the segment, the vote does not contain a full node, just a reference
type HotStuffVote struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Digest               []byte   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotStuffVote) Reset()         { *m = HotStuffVote{} }
func (m *HotStuffVote) String() string { return proto.CompactTextString(m) }
func (*HotStuffVote) ProtoMessage()    {}
func (*HotStuffVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc32763174c5d02, []int{1}
}

func (m *HotStuffVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotStuffVote.Unmarshal(m, b)
}
func (m *HotStuffVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotStuffVote.Marshal(b, m, deterministic)
}
func (m *HotStuffVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotStuffVote.Merge(m, src)
}
func (m *HotStuffVote) XXX_Size() int {
	return xxx_messageInfo_HotStuffVote.Size(m)
}
func (m *HotStuffVote) XXX_DiscardUnknown() {
	xxx_messageInfo_HotStuffVote.DiscardUnknown(m)
}

var xxx_messageInfo_HotStuffVote proto.InternalMessageInfo

func (m *HotStuffVote) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HotStuffVote) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

type HotStuffQC struct {
	Height               int32         `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Node                 *HotStuffNode `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Signature            []byte        `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HotStuffQC) Reset()         { *m = HotStuffQC{} }
func (m *HotStuffQC) String() string { return proto.CompactTextString(m) }
func (*HotStuffQC) ProtoMessage()    {}
func (*HotStuffQC) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc32763174c5d02, []int{2}
}

func (m *HotStuffQC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotStuffQC.Unmarshal(m, b)
}
func (m *HotStuffQC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotStuffQC.Marshal(b, m, deterministic)
}
func (m *HotStuffQC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotStuffQC.Merge(m, src)
}
func (m *HotStuffQC) XXX_Size() int {
	return xxx_messageInfo_HotStuffQC.Size(m)
}
func (m *HotStuffQC) XXX_DiscardUnknown() {
	xxx_messageInfo_HotStuffQC.DiscardUnknown(m)
}

var xxx_messageInfo_HotStuffQC proto.InternalMessageInfo

func (m *HotStuffQC) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HotStuffQC) GetNode() *HotStuffNode {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *HotStuffQC) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type HotStuffProposal struct {
	Leader               int32         `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Node                 *HotStuffNode `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HotStuffProposal) Reset()         { *m = HotStuffProposal{} }
func (m *HotStuffProposal) String() string { return proto.CompactTextString(m) }
func (*HotStuffProposal) ProtoMessage()    {}
func (*HotStuffProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc32763174c5d02, []int{3}
}

func (m *HotStuffProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotStuffProposal.Unmarshal(m, b)
}
func (m *HotStuffProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotStuffProposal.Marshal(b, m, deterministic)
}
func (m *HotStuffProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotStuffProposal.Merge(m, src)
}
func (m *HotStuffProposal) XXX_Size() int {
	return xxx_messageInfo_HotStuffProposal.Size(m)
}
func (m *HotStuffProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_HotStuffProposal.DiscardUnknown(m)
}

var xxx_messageInfo_HotStuffProposal proto.InternalMessageInfo

func (m *HotStuffProposal) GetLeader() int32 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *HotStuffProposal) GetNode() *HotStuffNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type HotStuffNewView struct {
	View                 int32       `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Certificate          *HotStuffQC `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HotStuffNewView) Reset()         { *m = HotStuffNewView{} }
func (m *HotStuffNewView) String() string { return proto.CompactTextString(m) }
func (*HotStuffNewView) ProtoMessage()    {}
func (*HotStuffNewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cc32763174c5d02, []int{4}
}

func (m *HotStuffNewView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotStuffNewView.Unmarshal(m, b)
}
func (m *HotStuffNewView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotStuffNewView.Marshal(b, m, deterministic)
}
func (m *HotStuffNewView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotStuffNewView.Merge(m, src)
}
func (m *HotStuffNewView) XXX_Size() int {
	return xxx_messageInfo_HotStuffNewView.Size(m)
}
func (m *HotStuffNewView) XXX_DiscardUnknown() {
	xxx_messageInfo_HotStuffNewView.DiscardUnknown(m)
}

var xxx_messageInfo_HotStuffNewView proto.InternalMessageInfo

func (m *HotStuffNewView) GetView() int32 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *HotStuffNewView) GetCertificate() *HotStuffQC {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func init() {
	proto.RegisterType((*HotStuffNode)(nil), "protobufs.HotStuffNode")
	proto.RegisterType((*HotStuffVote)(nil), "protobufs.HotStuffVote")
	proto.RegisterType((*HotStuffQC)(nil), "protobufs.HotStuffQC")
	proto.RegisterType((*HotStuffProposal)(nil), "protobufs.HotStuffProposal")
	proto.RegisterType((*HotStuffNewView)(nil), "protobufs.HotStuffNewView")
}

func init() {
	proto.RegisterFile("hotstufforderer.proto", fileDescriptor_9cc32763174c5d02)
}

var fileDescriptor_9cc32763174c5d02 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x14, 0x64, 0xfb, 0xb5, 0xf9, 0xec, 0x6b, 0xd4, 0xb2, 0xd0, 0xba, 0x88, 0x87, 0x90, 0x83, 0x04,
	0x84, 0x08, 0xf5, 0xe0, 0x41, 0xf0, 0x50, 0x2f, 0x9e, 0x44, 0x57, 0xa8, 0xe0, 0x41, 0xd8, 0x34,
	0x2f, 0x4d, 0xa0, 0x74, 0xeb, 0xe6, 0xc5, 0xfe, 0x4a, 0xff, 0x93, 0xec, 0x36, 0x69, 0x8b, 0x58,
	0xd0, 0xd3, 0xee, 0xcc, 0xce, 0x30, 0xfb, 0xde, 0xc0, 0x20, 0xd7, 0x54, 0x52, 0x95, 0x65, 0xda,
	0xa4, 0x68, 0xd0, 0xc4, 0x4b, 0xa3, 0x49, 0xf3, 0xae, 0x3b, 0x92, 0x2a, 0x2b, 0x4f, 0x0f, 0x0d,
	0xbe, 0x57, 0x58, 0xd2, 0xfa, 0x25, 0xfc, 0x64, 0xe0, 0xdf, 0x6b, 0x7a, 0xb6, 0x9e, 0x07, 0x9d,
	0x22, 0x1f, 0x82, 0x97, 0x63, 0x31, 0xcb, 0x49, 0xb0, 0x80, 0x45, 0x1d, 0x59, 0x23, 0xce, 0xa1,
	0xfd, 0x51, 0xe0, 0x4a, 0xb4, 0x1c, 0xeb, 0xee, 0x56, 0xbb, 0x54, 0x06, 0x17, 0x24, 0xfe, 0x05,
	0x2c, 0xf2, 0x65, 0x8d, 0xf8, 0x39, 0x74, 0x12, 0x45, 0xd3, 0x5c, 0xb4, 0x03, 0x16, 0xf5, 0x46,
	0xfd, 0x78, 0x13, 0x1f, 0x8f, 0x2d, 0x2f, 0xd7, 0xcf, 0xfc, 0x1a, 0x7a, 0x53, 0x34, 0x54, 0x64,
	0xc5, 0x54, 0x11, 0x8a, 0x8e, 0x53, 0x0f, 0x76, 0xd4, 0xcd, 0xcf, 0x9e, 0xee, 0xe4, 0xae, 0x92,
	0x0b, 0xf8, 0xaf, 0x12, 0x6d, 0x08, 0x53, 0xe1, 0x05, 0x2c, 0x3a, 0x90, 0x0d, 0x0c, 0x6f, 0xb7,
	0xe3, 0x4c, 0x34, 0xed, 0x1f, 0x67, 0x08, 0x5e, 0x5a, 0xcc, 0xb0, 0x24, 0x37, 0x90, 0x2f, 0x6b,
	0x14, 0x6a, 0x80, 0x6d, 0xe8, 0x5e, 0xf7, 0x05, 0xb4, 0x17, 0x3a, 0x45, 0xe7, 0xed, 0x8d, 0x4e,
	0x7e, 0xf8, 0xb1, 0xdd, 0xa5, 0x74, 0x22, 0x7e, 0x06, 0xdd, 0xb2, 0x98, 0x2d, 0x14, 0x55, 0x06,
	0xeb, 0x45, 0x6d, 0x89, 0xf0, 0x05, 0xfa, 0x8d, 0xe7, 0xd1, 0xe8, 0xa5, 0x2e, 0xd5, 0xdc, 0xc6,
	0xce, 0x51, 0xa5, 0x68, 0x9a, 0xd8, 0x35, 0xfa, 0x53, 0x6c, 0xf8, 0x06, 0xc7, 0x1b, 0x16, 0x57,
	0x13, 0xdb, 0x57, 0xd3, 0x21, 0xdb, 0xe9, 0xf0, 0x5b, 0x07, 0xad, 0xdf, 0x76, 0x30, 0x3e, 0x7a,
	0xf5, 0xe3, 0xcb, 0x9b, 0x8d, 0x2e, 0xf1, 0xdc, 0xf5, 0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xe9,
	0xeb, 0xf4, 0xec, 0x83, 0x02, 0x00, 0x00,
}
